### ISSUE TITLE
Release Alpha

### ISSUE THREAD

**Issue by LukasThijs** [Xablu/Xablu.WebApiClient#51]
If we want to release the first alpha version of the new features we should should finish the following requirements:

- [x] Implement native handler for HttpClient -> issue #47 

- [x] Implement Polly policies for GraphQL calls -> issue #43 

- [x] Implement multi-target approach -> #53
 
- [x] Test all new features and fixes. 

When all tasks are marked as resolved we can start the build and release process.
